# Generated by Django 5.2.6 on 2025-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated list of technologies', max_length=300)),
                ('link', models.URLField(blank=True, help_text='Live site or repository link', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('year', models.PositiveIntegerField(help_text='Year the project was completed')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
