services:
  - type: web
    name: fekadu-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fekadu_backend.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.vercel.app
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
